(global-set-key (kbd "<f5>") #'deft)
(global-set-key (kbd "<f6>") #'magit-status)
(global-set-key (kbd "<f8>")
		(lambda () "Open todo file" (interactive)
		  (find-file (concat user-emacs-directory "todo.org"))))
(global-set-key (kbd "<f9>")
		(lambda () "Open init file" (interactive)
		  (find-file (concat user-emacs-directory "init.el"))))
